#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rdiscount
Version  : 2.1.8
Release  : 5
URL      : https://rubygems.org/downloads/rdiscount-2.1.8.gem
Source0  : https://rubygems.org/downloads/rdiscount-2.1.8.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: rubygem-rdiscount-bin
Requires: rubygem-rdiscount-lib
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
Discount Markdown Processor for Ruby
====================================
[![Build Status](https://travis-ci.org/davidfstr/rdiscount.png)](https://travis-ci.org/davidfstr/rdiscount)

%package bin
Summary: bin components for the rubygem-rdiscount package.
Group: Binaries

%description bin
bin components for the rubygem-rdiscount package.


%package lib
Summary: lib components for the rubygem-rdiscount package.
Group: Libraries

%description lib
lib components for the rubygem-rdiscount package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rdiscount-2.1.8
gem spec %{SOURCE0} -l --ruby > rubygem-rdiscount.gemspec

%build
gem build rubygem-rdiscount.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rdiscount-2.1.8.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/rdiscount-2.1.8
ruby -v -I.:lib test*/*_test.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/rdiscount-2.1.8.gem
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/Object/sized_int-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/autolink-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/cdesc-RDiscount.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/filter_html-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/filter_styles-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/fold_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/footnotes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/generate_toc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/no_image-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/no_links-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/no_pseudo_protocols-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/no_strikethrough-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/no_superscript-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/no_tables-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/safelink-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/smart-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/strict-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/to_html-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RDiscount/toc_content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/RbConfig/cdesc-RbConfig.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/ext/page-Makefile.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/ext/page-VERSION.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/ext/page-blocktags.ri
/usr/lib64/ruby/gems/2.2.0/doc/rdiscount-2.1.8/ri/page-COPYING.ri
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/rdiscount-2.1.8/gem.build_complete
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/rdiscount-2.1.8/gem_make.out
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/rdiscount-2.1.8/mkmf.log
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/BUILDING
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/COPYING
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/README.markdown
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/bin/rdiscount
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/.RUBYARCHDIR.time
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/Csio.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/Csio.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/Makefile
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/VERSION
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/amalloc.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/amalloc.h
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/amalloc.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/basename.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/basename.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/blocktags
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/config.h
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/css.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/css.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/cstring.h
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/docheader.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/docheader.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/dumptree.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/dumptree.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/emmatch.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/emmatch.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/extconf.rb
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/flags.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/flags.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/generate.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/generate.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/github_flavoured.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/github_flavoured.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/html5.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/html5.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/markdown.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/markdown.h
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/markdown.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/mkdio.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/mkdio.h
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/mkdio.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/mktags.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/mktags.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/pgm_options.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/pgm_options.h
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/pgm_options.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/rdiscount.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/rdiscount.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/resource.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/resource.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/ruby-config.h
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/setup.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/setup.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/tags.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/tags.h
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/tags.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/toc.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/toc.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/version.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/version.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/xml.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/xml.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/xmlpage.c
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/xmlpage.o
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/lib/markdown.rb
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/lib/rdiscount.rb
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/man/markdown.7
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/man/rdiscount.1
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/man/rdiscount.1.ronn
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/rdiscount.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/test/benchmark.rb
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/test/benchmark.txt
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/test/markdown_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/test/rdiscount_test.rb
/usr/lib64/ruby/gems/2.2.0/specifications/rdiscount-2.1.8.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/rdiscount

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/rdiscount-2.1.8/rdiscount.so
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/ext/rdiscount.so
/usr/lib64/ruby/gems/2.2.0/gems/rdiscount-2.1.8/lib/rdiscount.so
